# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'truck.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import cv2, imutils
import time
import sys



class MyThread(QThread):
    frame_signal = pyqtSignal(QImage)

    def run(self):
        self.cap = cv2.VideoCapture(0)
        while self.cap.isOpened():
            _,frame = self.cap.read()
            frame = self.cvimage_to_label(frame)
            self.frame_signal.emit(frame)
    
    def cvimage_to_label(self,image):
        image = imutils.resize(image,width = 300)
        image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
        image = QImage(image,
                       image.shape[1],
                       image.shape[0],
                       QImage.Format_RGB888)
        return image



class Ui_Dialog(QMainWindow):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1474, 847)
        self.img_full = QLabel(Dialog)
        self.img_full.setGeometry(QRect(220, 40, 311, 141))
        self.img_full.setMinimumSize(QSize(135, 96))
        self.img_full.setAlignment(Qt.AlignCenter)
        self.img_full.setObjectName("img_full")
        self.dname = QLabel(Dialog)
        self.dname.setGeometry(QRect(340, 10, 67, 17))
        self.dname.setObjectName("dname")
        self.img_sel = QLabel(Dialog)
        self.img_sel.setGeometry(QRect(30, 200, 191, 121))
        self.img_sel.setMinimumSize(QSize(135, 96))
        self.img_sel.setAlignment(Qt.AlignCenter)
        self.img_sel.setObjectName("img_sel")
        self.img_pred = QLabel(Dialog)
        self.img_pred.setGeometry(QRect(270, 200, 191, 121))
        self.img_pred.setMinimumSize(QSize(135, 96))
        self.img_pred.setAlignment(Qt.AlignCenter)
        self.img_pred.setObjectName("img_pred")
        self.img_driv = QLabel(Dialog)
        self.img_driv.setGeometry(QRect(500, 200, 191, 121))
        self.img_driv.setMinimumSize(QSize(135, 96))
        self.img_driv.setAlignment(Qt.AlignCenter)
        self.img_driv.setObjectName("img_driv")
        self.temp_simu = QLabel(Dialog)
        self.temp_simu.setGeometry(QRect(30, 340, 661, 101))
        self.temp_simu.setMinimumSize(QSize(135, 96))
        self.temp_simu.setAlignment(Qt.AlignCenter)
        self.temp_simu.setObjectName("temp_simu")
        self.temp_bio = QLabel(Dialog)
        self.temp_bio.setGeometry(QRect(30, 470, 661, 101))
        self.temp_bio.setMinimumSize(QSize(135, 96))
        self.temp_bio.setAlignment(Qt.AlignCenter)
        self.temp_bio.setObjectName("temp_bio")
        self.tem_hmes = QLabel(Dialog)
        self.tem_hmes.setGeometry(QRect(30, 600, 661, 101))
        self.tem_hmes.setMinimumSize(QSize(135, 96))
        self.tem_hmes.setAlignment(Qt.AlignCenter)
        self.tem_hmes.setObjectName("tem_hmes")
        self.lab_msg = QLabel(Dialog)
        self.lab_msg.setGeometry(QRect(30, 790, 67, 17))
        self.lab_msg.setObjectName("lab_msg")
        self.edt_msg = QPlainTextEdit(Dialog)
        self.edt_msg.setGeometry(QRect(170, 770, 351, 51))
        self.edt_msg.setObjectName("edt_msg")
        self.img_full_2 = QLabel(Dialog)
        self.img_full_2.setGeometry(QRect(960, 30, 311, 141))
        self.img_full_2.setMinimumSize(QSize(135, 96))
        self.img_full_2.setAlignment(Qt.AlignCenter)
        self.img_full_2.setObjectName("img_full_2")
        self.tem_hmes_2 = QLabel(Dialog)
        self.tem_hmes_2.setGeometry(QRect(770, 590, 661, 101))
        self.tem_hmes_2.setMinimumSize(QSize(135, 96))
        self.tem_hmes_2.setAlignment(Qt.AlignCenter)
        self.tem_hmes_2.setObjectName("tem_hmes_2")
        self.img_sel_2 = QLabel(Dialog)
        self.img_sel_2.setGeometry(QRect(770, 190, 191, 121))
        self.img_sel_2.setMinimumSize(QSize(135, 96))
        self.img_sel_2.setAlignment(Qt.AlignCenter)
        self.img_sel_2.setObjectName("img_sel_2")
        self.temp_bio_2 = QLabel(Dialog)
        self.temp_bio_2.setGeometry(QRect(770, 460, 661, 101))
        self.temp_bio_2.setMinimumSize(QSize(135, 96))
        self.temp_bio_2.setAlignment(Qt.AlignCenter)
        self.temp_bio_2.setObjectName("temp_bio_2")
        self.img_driv_2 = QLabel(Dialog)
        self.img_driv_2.setGeometry(QRect(1240, 190, 191, 121))
        self.img_driv_2.setMinimumSize(QSize(135, 96))
        self.img_driv_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.img_driv_2.setObjectName("img_driv_2")
        self.temp_simu_2 = QLabel(Dialog)
        self.temp_simu_2.setGeometry(QRect(770, 330, 661, 101))
        self.temp_simu_2.setMinimumSize(QSize(135, 96))
        self.temp_simu_2.setAlignment(Qt.AlignCenter)
        self.temp_simu_2.setObjectName("temp_simu_2")
        self.img_pred_2 = QLabel(Dialog)
        self.img_pred_2.setGeometry(QRect(1010, 190, 191, 121))
        self.img_pred_2.setMinimumSize(QSize(135, 96))
        self.img_pred_2.setAlignment(Qt.AlignCenter)
        self.img_pred_2.setObjectName("img_pred_2")
        self.lab_msg_2 = QLabel(Dialog)
        self.lab_msg_2.setGeometry(QRect(770, 780, 67, 17))
        self.lab_msg_2.setObjectName("lab_msg_2")
        self.dname_2 = QLabel(Dialog)
        self.dname_2.setGeometry(QRect(1080, 0, 67, 17))
        self.dname_2.setObjectName("dname_2")
        self.edt_msg_2 = QPlainTextEdit(Dialog)
        self.edt_msg_2.setGeometry(QRect(910, 760, 351, 51))
        self.edt_msg_2.setObjectName("edt_msg_2")
        self.btn_msg_send = QPushButton(Dialog)
        self.btn_msg_send.setGeometry(QRect(540, 780, 89, 25))
        self.btn_msg_send.setObjectName("btn_msg_send")
        self.btn_msg_send_2 = QPushButton(Dialog)
        self.btn_msg_send_2.setGeometry(QRect(1280, 770, 89, 25))
        self.btn_msg_send_2.setObjectName("btn_msg_send_2")
        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)


        self.default_img(self.img_full, 'Images/220.png')
        self.default_img(self.img_sel, 'Images/220_resize.png')
        self.default_img(self.img_pred, 'Images/220_road_resize.png')
        self.default_img(self.img_driv, 'Images/driv.jpg')
        # self.update_info(self.img_driv)
        self.camera_thread = MyThread()
        self.camera_thread.frame_signal.connect(self.setImage)
    

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.img_full.setText(_translate("Dialog", "Full Image"))
        self.dname.setText(_translate("Dialog", "Driver 1"))
        self.img_sel.setText(_translate("Dialog", "Selected"))
        self.img_pred.setText(_translate("Dialog", "Predicted"))
        self.img_driv.setText(_translate("Dialog", "Driver"))
        self.temp_simu.setText(_translate("Dialog", "Simulation Info"))
        self.temp_bio.setText(_translate("Dialog", "Bio Info"))
        self.tem_hmes.setText(_translate("Dialog", "Prev Messgaes"))
        self.lab_msg.setText(_translate("Dialog", "TextLabel"))
        self.img_full_2.setText(_translate("Dialog", "Full Image"))
        self.tem_hmes_2.setText(_translate("Dialog", "Prev Messgaes"))
        self.img_sel_2.setText(_translate("Dialog", "Selected"))
        self.temp_bio_2.setText(_translate("Dialog", "Bio Info"))
        self.img_driv_2.setText(_translate("Dialog", "Driver"))
        self.temp_simu_2.setText(_translate("Dialog", "Simulation Info"))
        self.img_pred_2.setText(_translate("Dialog", "Predicted"))
        self.lab_msg_2.setText(_translate("Dialog", "TextLabel"))
        self.dname_2.setText(_translate("Dialog", "Driver 2"))        
        self.btn_msg_send.setText(_translate("Dialog", "Send"))
        self.btn_msg_send_2.setText(_translate("Dialog", "Send"))
        self.btn_msg_send.clicked.connect(self.open_camera)

    def default_img(self, img_holder, path):
        img = cv2.imread(path)

        self.show_image(img_holder, img)

    def show_image(self, img_holder, img):
        image = QImage(img, img.shape[1],img.shape[0], img.shape[1] * 3, QImage.Format_BGR888)

        pixmap = QPixmap(image)
        pixmap =  pixmap.scaled(300, 150, Qt.KeepAspectRatio)
        img_holder.setPixmap(pixmap)

    def open_camera(self):        
        self.camera_thread.start()
        print(self.camera_thread.isRunning())

    @pyqtSlot(QImage)
    def setImage(self,image):
        self.img_driv.setPixmap(QPixmap.fromImage(image))



if __name__ == "__main__":
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
